cd alter_vschet
call build.cmd
call deploy.cmd
cd ..\bnk
call build.cmd
call deploy.cmd
cd ..\debitor
call build.cmd
call deploy.cmd
cd ..\frm
call build.cmd
call deploy.cmd
cd ..\gui
call build.cmd
call deploy.cmd
cd ..\l_dogovor
call build.cmd
call deploy.cmd
cd ..\l_skid
call build.cmd
call deploy.cmd
cd ..\marshruts
call build.cmd
call deploy.cmd
cd ..\pack
call build.cmd
call deploy.cmd
cd ..\real
call build.cmd
call deploy.cmd
cd ..\sale
call build.cmd
call deploy.cmd
cd ..\usr
call build.cmd
call deploy.cmd
cd ..\xml
call build.cmd
call deploy.cmd
