#define mycTerrFrm 8
#define mycDopTblTerrFrm 1
#define mycRegNal 9
#define mycDopENVD 3

Const
  mycTerr = 8;
  mycRegNal = 9;
  mycObjType = 11;
  mycModType = 1;
  mycDopTblTerr = 1;
  mycDopKodBud = 2;
  mycDopENVD =3;
  mycCodeRegnalPart = '1';
  mycCodeRegnal100 ='2';
  myVmenNalog1 = 2;
  myVmenNalog2 = 4;
  myVmenNalog3 = 6;
  myVmenNalog4 = 7;
  mySchVmen100 = '25';  
  mySubschVmen100 = '';
  myUserAnARM = 257;
  mySpkautblcode = 8512;
  mycPdrRukKod = '8.000.00000';
  myNoTerrString = 'Не выбраны терр.принадл.';
  myNoRegNalString = 'Не выбраны режимы налогообложения';
  myNoGrRabString = 'Не выбраны группы работников';