/*
 ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
 บ                     (c) 1994,98 ฎเฏฎเ ๆจ๏ €€’€                      บ
 บ เฎฅชโ        : €€’€                                                 บ
 บ ฅเแจ๏        : 5.50                                                      บ
 บ  งญ ็ฅญจฅ    : ไ ฉซ แฎ ขแฅฌจ ญฅฎกๅฎคจฌ๋ฌจ ชฎญแโ ญโ ฌจ                    บ
 บ โขฅโแโขฅญญ๋ฉ : ฎซฎค์ชฎ  คจฌ ฅญญ ค์ฅขจ็                                บ
 ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
*/
#include D:\Compile\8.1\Inc\galhelp.inc

! const
#include D:\Compile\8.1\Inc\buhconst.inc
#include D:\Compile\8.1\Inc\Excel.inc
#include D:\Compile\8.1\Inc\KatDoc.inc    // ฎญแโ ญโ๋ คซ๏ โจฏฎข คฎชใฌฅญโฎข
#include D:\Compile\8.1\Inc\kauconst.inc
#include D:\Compile\8.1\Inc\treenew.inc
#include D:\Compile\8.1\Inc\gloconst.inc
#include D:\Compile\8.1\Inc\fldcolor.inc
#include D:\Compile\8.1\Inc\reptree.inc
#include D:\Compile\8.1\Inc\money.ccm
!-----------------------------------------
! ชฎญแโ ญโ๋ ฏฎซ์งฎข โฅซ์แชจๅ ชฎฌ ญค
#include D:\Compile\8.1\inc\galnet.ccm
!-----------------------------------------
! ชฎญแโ ญโ๋ แโ โใแ-แโเฎช  ซ ชโจชจ
#include D:\Compile\8.1\Inc\GALNET.CSC
#include D:\Compile\8.1\Inc\pick.inc
