Const
  // Константы для перечня полей в настройках алгоритма
  // пересчета полей путевого листа

  // первая группа полей
  cppExitCh   = 1;
  cppExitDn   = 2;
  cppSpeedExi = 3;
  cppNpVirVal = 4;

  // вторая группа полей
  cppReturnCh = 1;
  cppReturnDn = 2;
  cppSpeedRet = 3;
  cppFkVirVal = 4;

  // третья группа полей
  cppTimeLoad    = 1;
  cppTimeStop    = 2;
  cppTimeRep     = 3;
  cppTimeEngine  = 4;
  cppTimeVolume0 = 5;
  cppTimeHeat    = 6;
  cppTimeSpec    = 7;
  cppTimePg      = 8;
  cppReal_ExitCh = 9;
  cppReal_ExitDn = 10;
  cppTimeDn      = 11;

  // четвертая группа полей
  cppProbegAll  = 1;
  cppProbegGr   = 2;
  cppProbegV    = 3;
  cppGruzTn     = 4;
  cppGruzTnKm   = 5;
  cppKoffProbeg = 6;
  cppProbeg2    = 7;
  cppVolWrk     = 8;
  cppReal_ReturnCh  = 9;
  cppReal_ReturnDn  = 10;

  // пятая группа полей
  cppDPPOKAZ4   = 1;
  cppPOK1RB     = 2;
  cppPOK2RB     = 3;
  cppTIMERZ     = 4;
  cppPOK1CNG    = 5;
  cppPOK2CNG    = 6;
  cppPROBEGTAM  = 7;
  cppPOK1INO    = 8;
  cppPOK2INO    = 9;
  cppPRPRC      = 10;
  cppDPPOKAZ5   = 11;
  cppTIMEDEF    = 12;

  // шестая группа полей
 cppPOK3CNG = 1;
 cppPOK3RB  = 2;
 cppPOK4RB  = 3;
 cppPOK5INO = 4;
 cppPOK3INO = 5;
