//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика ERP 9.1 - Управление персоналом
// Константы для разделения сущностей таблицы SpAllStaff по полю SpAllStaff.wNoCon
//------------------------------------------------------------------------------

cgAllStaffProtocol = 1; // для протокола сообщений
cgAllStaffCandidatDX = 3;
cgAllStaffImportSAP = 4; // для протокола сообщений при импорте из SAP
cgAllStaffContract = 5;
cgAllStaffAddAgreement = 6;
cgAllStaffAgreementLink = 7;
cgHAppHRaiseCon         = 8;
cgAppRaiseCon           = 9;
cgAllStaffCatLiquidation = 10;
cgUserEventTune          = 11; // Блокнот событий: настройка роли блокнота событий для пользователей
cgUserReminder           = 12; // Блокнот событий: сохраненные напоминания пользователей-отправителей
cgAllStaffLinkHistorySHR = 13;