//------------------------------------------------------------------------------
//                                                      (c) корпорация Галактика
// Галактика 9.10 - модуль "Электронная отчетность"
// Глобальные константы модуля
//------------------------------------------------------------------------------

cgiTaxCatalog_All  = 0;

cgiTaxCat_TranD = 1;
cgsTaxCat_TranD = 'TaxCatalog_Transp';

cgiTaxCat_OKVED = 2;
cgsTaxCat_OKVED = 'TaxCatalog_OKVED';

cgiTaxCat_KodPT = 3;
cgsTaxCat_KodPT = 'TaxCatalog_KodPT';

cgiTaxCat_Imush = 4;
cgsTaxCat_Imush = 'TaxCatalog_Imush';

cgiTaxCat_KodVidOper = 5;
cgsTaxCat_KodVidOper = 'TaxCatalog_KodVidOper';

cgiTaxCat_Zem = 6;
cgsTaxCat_Zem = 'TaxCatalog_Zem';

cgiTaxCat_NDS_R3P1 = 7;
cgsTaxCat_NDS_R3P1 = 'TaxCatalog_NDS_R3P1';

cgiTaxCat_KodOperNDS = 8;
cgsTaxCat_KodOperNDS = 'TaxCatalog_KodOperNDS';

cgiTaxCat_TranspRate = 9;
cgsTaxCat_TranspRate = 'TaxCatalog_RateCatEntity';

//константы для отбора объектов-справочников
cgsTax_IfcPrefixCat  = 'TaxCatalog_';
cgsTax_ObjIfcNameCat = 'F_TaxReport::oTaxCatalog';
cgsTax_ResNameCat = 'F_TaxReport::';

// константы налогового календаря
cgiCldrTxDeliv  = 0; // запись сдачи налогового отчета
cgiCldrTxPay    = 1;


