//******************************************************************************
//                                                      (c) корпорация Галактика
// Галактика 7.12 - Логистика
// для Транзакций подключается во from
//******************************************************************************

// !!! все изменения должны быть синхронизированы с reread.vpp

  ras_ord
, SklOrder
, SpOrder
, KatParty
, KatPodr
, KatSopr
, SpSopr
, SoprHoz
, Oborot
, BaseDoc
, StepDoc
, SpStep
, DoRes
, TekSaldo
, SklOst
, KatMC
, TekMc
, KatOtpEd(ReadOnly)
, KatEd(ReadOnly)
, Kontras
, KlVal(ReadOnly)
, CursVal(ReadOnly)
, KatNazna
